name: MultiBreak
version: '${version}'
main: me.vermulst.multibreak.Main
api-version: '1.20'
permissions:
  multibreak.admin:
    default: op
commands:
  multibreak:
    description: multi break
    usage: /multibreak
    permission: multibreak.admin
  multipreset:
    description: create a multibreak config to apply fast
    usage: /multiconfig
    permission: multibreak.admin
    aliases: [multiconfiguration]
  multireload:
    description: reload the multibreak config
    usage: /multireload
    permission: multibreak.admin